## Nexys A7 constraints template (fill in pins as needed)
## Clock: 50 MHz

# Clock input
set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name sys_clk -waveform {0.000 5.000} [get_ports clk]

# Reset (active-low)
set_property PACKAGE_PIN M17 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

# BOOTLOADER UART RX
set_property PACKAGE_PIN C4 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports rx]

# BOOTLOADER UART TX
set_property PACKAGE_PIN D4 [get_ports tx]
set_property IOSTANDARD LVCMOS33 [get_ports tx]

# Status LED (active-low)
set_property PACKAGE_PIN R11 [get_ports led_status]
set_property IOSTANDARD LVCMOS33 [get_ports led_status]

# GPIO Pins
# SW0 - SW15
set_property PACKAGE_PIN J15 [get_ports {pin_gpio[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[0]}]
set_property PACKAGE_PIN L16 [get_ports {pin_gpio[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[1]}]
set_property PACKAGE_PIN M13 [get_ports {pin_gpio[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[2]}]
set_property PACKAGE_PIN R15 [get_ports {pin_gpio[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[3]}]
set_property PACKAGE_PIN R17 [get_ports {pin_gpio[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[4]}]
set_property PACKAGE_PIN T18 [get_ports {pin_gpio[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[5]}]
set_property PACKAGE_PIN U18 [get_ports {pin_gpio[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[6]}]
set_property PACKAGE_PIN R13 [get_ports {pin_gpio[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[7]}]
set_property PACKAGE_PIN T8 [get_ports {pin_gpio[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[8]}]
set_property PACKAGE_PIN U8 [get_ports {pin_gpio[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[9]}]
set_property PACKAGE_PIN R16 [get_ports {pin_gpio[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[10]}]
set_property PACKAGE_PIN T13 [get_ports {pin_gpio[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[11]}]
set_property PACKAGE_PIN H6 [get_ports {pin_gpio[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[12]}]
set_property PACKAGE_PIN U12 [get_ports {pin_gpio[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[13]}]
set_property PACKAGE_PIN U11 [get_ports {pin_gpio[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[14]}]
set_property PACKAGE_PIN V10 [get_ports {pin_gpio[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[15]}]

# LED0 - LED15 (Nexys A7)
set_property PACKAGE_PIN H17 [get_ports {pin_gpio[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[16]}]
set_property PACKAGE_PIN K15 [get_ports {pin_gpio[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[17]}]
set_property PACKAGE_PIN J13 [get_ports {pin_gpio[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[18]}]
set_property PACKAGE_PIN N14 [get_ports {pin_gpio[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[19]}]
set_property PACKAGE_PIN R18 [get_ports {pin_gpio[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[20]}]
set_property PACKAGE_PIN V17 [get_ports {pin_gpio[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[21]}]
set_property PACKAGE_PIN U17 [get_ports {pin_gpio[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[22]}]
set_property PACKAGE_PIN U16 [get_ports {pin_gpio[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[23]}]
set_property PACKAGE_PIN V16 [get_ports {pin_gpio[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[24]}]
set_property PACKAGE_PIN T15 [get_ports {pin_gpio[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[25]}]
set_property PACKAGE_PIN U14 [get_ports {pin_gpio[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[26]}]
set_property PACKAGE_PIN T16 [get_ports {pin_gpio[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[27]}]
set_property PACKAGE_PIN V15 [get_ports {pin_gpio[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[28]}]
set_property PACKAGE_PIN V14 [get_ports {pin_gpio[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[29]}]
set_property PACKAGE_PIN V12 [get_ports {pin_gpio[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[30]}]
set_property PACKAGE_PIN V11 [get_ports {pin_gpio[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin_gpio[31]}]
